### Teste da API Question API

# GET - Listar todos os usuários
GET http://localhost:3000/user

###

# POST - Criar novo usuário
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "João Silva",
  "email": "joao@email.com",
  "password": "senha123"
}
###

# POST - Login
POST http://localhost:3000/auth/login
Content-Type: application/json


{
  "email": "joao@email.com",
  "password": "senha123"
}

###

# GET - Listar usuário por ID
GET http://localhost:3000/user/136b3ce2-3fc7-407f-bb5b-3b71863e76e3
Content-Type: application/json

###

# POST - Criar outro usuário para teste
POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Maria Santos",
  "email": "maria@email.com",
  "password": "senha456"
}
