version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: question_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: question_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - question_api_network

volumes:
  postgres_data:
    driver: local

networks:
  question_api_network:
    driver: bridge
